version: "3.1"

services:
    db:
        image: mysql:8
        platform: linux/x86_64
        ports:
            - 3306:3306
        volumes:
            - ./database/mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=web2
            - MYSQL_ROOT_PASSWORD=root

    redis:
        image: redis:alpine
        platform: linux/x86_64
        ports:
            - 6379:6379
        volumes:
            - ./database/redis:/data
