name: run-test
on: [push]
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Run composer
        run: composer install -n --prefer-dist

      - name: Prepare laravel application
        run: php artisan --env=testing key:generate
        env:
          DB_DATABASE: ${GITHUB_WORKSPACE}/database/testing.sqlite

      - name: Run Test
        run: php artisan test --env=testing --filter BarangTest
        env:
          DB_DATABASE: ${GITHUB_WORKSPACE}/database/testing.sqlite
